name: Push mobile application on firebase for people to build
'on':
  push:
    branches:
      - main
      - "*"

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  deploy_android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 100
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: "Setup Gradle"
        uses: gradle/gradle-build-action@v2
      - name: "Build retrieve the version"
        run: |
          ./gradlew versionEnv 
          # export the variable in the file as pipeline env
          cat version.env >> "$GITHUB_ENV"
      - name: "Build bundle release"
        run: ./gradlew android:bundleRelease
      - name: "Credentials"
        run: |
          printf "${{ secrets.KNEWS_ACCOUNT_JSON_KEY}}\n" > google_account_key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$PWD/google_account_key.json" >> "$GITHUB_ENV"
      - name: "Push release"
        run: ./gradlew assembleRelease appDistributionUploadRelease