jobs:
  deploy_ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: "Setup Gradle"
        uses: gradle/gradle-build-action@v2
      - name: "Build xcworkspace"
        run: ./gradlew versionEnv && source version.env
      - name: "Setup app version"
        uses: yanamura/ios-bump-version@v1
        with:
          version: ${{ env.APP_VERSION_NAME }}
          build-number: ${{ env.APP_VERSION_CODE }}
          project-path: iosApp
      - name: "Build iOS App"
        uses: yukiarrr/ios-build-action@v1.9.1
        with:
          project-path: iosApp/iosApp.xcodeproj
          p12-base64: ${{ secrets.APPLE_DEV_P12_CERT_B64 }}
          mobileprovision-base64: ${{ secrets.PROD_MIXDRINKS_IOS_BUILD_PROVISION_PROFILE_BASE64 }}
          code-signing-identity: "iPhone Distribution"
          team-id: ${{ secrets.ZUHLKE_IOS_TEAM_ID }}
          certificate-password: ${{ secrets.APPLE_DEV_CERT_PASSWORD }}
          export-options: iosApp/exportOptionsRelease.plist
          workspace-path: iosApp/iosApp.xcworkspace
          export-method: "app-store"