# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: News KMP release pipeline
on:
  push:
    tags:
      - '*'
permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: read
      checks: write
      pull-requests: write
    outputs:
      upload_url:  ${{ steps.create_release.outputs.upload_url }}
    steps:
    - uses: actions/checkout@v3
    - name: release
      uses: "marvinpinto/action-automatic-releases@latest"
      id: create_release
      with:
        repo_token: ${{ github.token }}
        prerelease: false

#  linux:
#    runs-on: ubuntu-latest
#    needs:
#      - release
#    permissions:
#      contents: write
#      issues: read
#      checks: write
#      pull-requests: write
#    steps:
#      - uses: actions/checkout@v3
#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#      - name: Build with Gradle
#        uses: gradle/gradle-build-action@v2.6.0
#        with:
#          arguments: test
#      - name: Install rpm
#        uses: ConorMacBride/install-package@v1
#        with:
#          apt: rpm
#      - name: Build release
#        uses: gradle/gradle-build-action@v2.6.0
#        with:
#          arguments: packageDistributionForCurrentOs
#      - name: upload linux artifact
#        uses: actions/upload-release-asset@v1
#        with:
#          upload_url: ${{ needs.release.outputs.upload_url }}
#          asset_path: build/compose/binaries/main/dpmg/News-${{ github.ref_name }}-1.x86_64.rpm
#          asset_name: kpassword-store-${{ github.ref_name  }}-1.x86_64.rpm
#          asset_content_type: application/octet-stream
#        env:
#          GITHUB_TOKEN: ${{ github.token }}
#      - uses: actions/upload-artifact@v3
#        with:
#          path: build/compose/binaries/main/rpm/*

  mac:
    runs-on: macos-latest
    needs:
      - release
    permissions:
      contents: write
      issues: read
      checks: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: show java version
        run: java --version
      - name: make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.6.0 # v2.6.0
        with:
          arguments: packageDistributionForCurrentOs

      - name: upload mac artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: desktopApp/build/compose/binaries/main/dmg/News-${{ github.ref_name}}.dmg
          asset_name: News-${{ github.ref_name }}.dmg
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ github.token }}

  windows:
    runs-on: windows-latest
    needs:
      - release
    permissions:
      contents: write
      issues: read
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: show java version
        run: java --version
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.6.0
      - name: package
        run: ./gradlew packageDistributionForCurrentOs -i

      - name: upload windows artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: desktopApp/build/compose/binaries/main/msi/News-${{ github.ref_name}}.msi
          asset_name: News-${{ github.ref_name }}.msi
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ github.token }}