name: Tag for release
on:
  workflow_dispatch:
    inputs:
      preRelease:
        description: 'Pre release tag, "-" for a release, nothing for the default behaviour'
        required: false
        type: string

permissions:
  contents: read

jobs:
  tag-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: read
      checks: write
      pull-requests: write
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: create tag for pre-release ${{inputs.preRelease}}
        if: inputs.preRelease != ''
        run: ./gradlew releaseVersion --preRelease=${{inputs.preRelease}}
      - name: create tag for next release
        if: inputs.preRelease == ''
        run: ./gradlew releaseVersion
      - name: push tag
        run: |
          git push
          git push --tags

