name: News KMP release pipeline
on:
  workflow_dispatch:
    branch:
      - main


permissions:
  contents: read

jobs:
  tag-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: read
      checks: write
      pull-requests: write
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: create tag
        run: ./gradlew releaseVersion --preRelease=-
      - name: push tag
        run: |
          git push
          git push --tags

